/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package syslabcontrol;

import java.util.ArrayList;
import java.util.Iterator;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import java.awt.FileDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USB_Room
 */
public class DefinitionsPanel extends javax.swing.JPanel{

    /**
     * Creates new form DefinitionsPanel
     */
    
    ArrayList <ChannelPanel> chanPanList;
    Terminal terminal;
    final SequenceEditor parentFrame;
    
    public DefinitionsPanel(SequenceEditor parentFrame) {
        
        this.terminal = parentFrame.getTerminal();
        this.parentFrame = parentFrame;
        
        
        chanPanList = new ArrayList();
        
        initComponents();
        
        buildPanel();
        
    }
    public void buildPanel() {
        //each group gets its own channel panel;
        
        jTabbedPane1.removeAll();
        this.chanPanList = new <ChannelPanel> ArrayList();
        
        for (ChannelGroup g : parentFrame.sequence.groups) 
        {
            ChannelPanel ch = new ChannelPanel(g,terminal);
            jTabbedPane1.add(g.groupName, ch);
            chanPanList.add(ch);
        }           
    }
    public void syncAllTables()
    {
        Iterator i = chanPanList.iterator();
        while(i.hasNext())
            ((ChannelPanel)i.next()).syncTable();
    }
   
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        addChannelButton = new javax.swing.JButton();
        addGroupButton = new javax.swing.JButton();
        removeGroupButton = new javax.swing.JButton();
        renameGroupButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setName("Define Groups"); // NOI18N

        jToolBar1.setRollover(true);

        saveButton.setText("Save");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(saveButton);

        loadButton.setText("Load");
        loadButton.setFocusable(false);
        loadButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loadButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(loadButton);
        jToolBar1.add(filler3);

        addChannelButton.setText("Add Channel");
        addChannelButton.setFocusable(false);
        addChannelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addChannelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addChannelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChannelButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addChannelButton);

        addGroupButton.setText("Add Group");
        addGroupButton.setFocusable(false);
        addGroupButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addGroupButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addGroupButton);

        removeGroupButton.setText("Remove Group");
        removeGroupButton.setFocusable(false);
        removeGroupButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeGroupButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGroupButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(removeGroupButton);

        renameGroupButton.setText("Rename Group");
        renameGroupButton.setFocusable(false);
        renameGroupButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        renameGroupButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        renameGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameGroupButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(renameGroupButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        parentFrame.sequence.saveState(this);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        parentFrame.sequence.loadState(this);
        parentFrame.updatePanelStates();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void addChannelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChannelButtonActionPerformed
        
        
        if (jTabbedPane1.getTabCount() == 0)
            return;
        ChannelPanel c = (ChannelPanel) jTabbedPane1.getComponentAt(jTabbedPane1.getSelectedIndex());
        
        c.addEmptyChannel();
        
        
    }//GEN-LAST:event_addChannelButtonActionPerformed

    private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupButtonActionPerformed
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
        String s = (String) JOptionPane.showInputDialog(parent, "New Group: Name?");
        if(s == null)
            return;
        parentFrame.sequence.groups.add(new ChannelGroup(s.trim()));
        parentFrame.updatePanelStates();
    }//GEN-LAST:event_addGroupButtonActionPerformed

    private void removeGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGroupButtonActionPerformed
        if (jTabbedPane1.getTabCount() == 0)
            return;
        
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
        int x = JOptionPane.showConfirmDialog(parent, "Are you sure you want to remove group?", "Confirm Removal...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if ( x == JOptionPane.YES_OPTION)
        {
            parentFrame.sequence.groups.remove(jTabbedPane1.getSelectedIndex());
            ((ChannelPanel)jTabbedPane1.getComponentAt(jTabbedPane1.getSelectedIndex())).removeGroup();
            jTabbedPane1.remove(jTabbedPane1.getSelectedIndex());
            
        }
        parentFrame.updatePanelStates();
    }//GEN-LAST:event_removeGroupButtonActionPerformed

    private void renameGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameGroupButtonActionPerformed
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
        String s = (String) JOptionPane.showInputDialog(parent, "New Group: Name?");
        if(s == null)
            return;
        ((ChannelPanel)jTabbedPane1.getComponentAt(jTabbedPane1.getSelectedIndex())).renameGroup(s);
        parentFrame.updatePanelStates();
    }//GEN-LAST:event_renameGroupButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChannelButton;
    private javax.swing.JButton addGroupButton;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton removeGroupButton;
    private javax.swing.JButton renameGroupButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    
}
